# Site settings
title: Psyche-Eros Rose Croix Chapter
email: chapter@chapteremail.com
description: > # this means to ignore newlines until "baseurl:"
  Official website for Psyche-Eros Rose Croix Chapter of Ordo Templi Orientis.
baseurl: "/jekylldemo" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  samekh93

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
